import Hero from '@/components/hero'
import Head from 'next/head'
import React from 'react'

export default function about() {
  return (
    <>
        <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>
            About
        </h2>
        <Hero/>
      </div>
    </>
  )
}
